logger: Fix logging error on deploy command
If --no-https is used, the deploy command will crash with:
  TypeError: info() missing 1 required positional argument: 'msg'

Change-Id: Iaac9576f9b01d0d51ae951f2c0bb386cb49c88cf